### PR TITLE
issue-4195 - Adjust reorder functionality

### LINKED ISSUE #4195: User can not make reorder of order from other store
**Description**:
user can not make reorder of order from other store, nothing appear on FE
message in console: "Order number "4000000059" doesn't belong to the current customer"

**Expected behavior**:
User can make reorder of any of his orders 

**Screenshots, Video, Logs**
https://vimeo.com/671173727/3e5d3b0a48

**To Reproduce**:

1. Open Store X
2. Log in with account A
3. Complete order 1
4. Open store Y
5. Log in with account A
6. Open My orders > Order 1 
7. Click on 'Reorder'

**Actual result**:
user can not make reorder of order from other store

### PR DESCRIPTION
**Pull request by AleksandrsKondratjevs**
**Related issue(s)**
* fixes scandipwa/scandipwa#4195

**Problems**
* User can't reorder if order was made in other store. On default magento it gets store id from order instead of current store.

**In this PR**
* Adjust reorder functionality

### CODE REVIEW

File: Model/Resolver/Reorder.php [hunk 1]
```diff
@@ -0,0 +1,102 @@
+<?php
+/**
```
Comment (aleksandrsm) [inline Model/Resolver/Reorder.php:2]: change copyright to PWA's

File: Model/Resolver/Reorder.php [hunk 2]
```diff
@@ -0,0 +1,102 @@
...
+{
+    /**
+     * Order number
+     */
+    public const ARGUMENT_ORDER_NUMBER = 'orderNumber';
+
+    /**
+     * @var OrderFactory
+     */
+    public $orderFactory;
```
Comment (aleksandrsm) [inline Model/Resolver/Reorder.php]: assume this will be tagged in latest PWA? then php 7.4 features - public OrderFactory $orderFactory;
same for other props

File: Model/Resolver/Reorder.php (hunk 1 above)
Comment (AleksandrsKondratjevs) [reply Model/Resolver/Reorder.php:2]: I see we have almost in all files docs from magento instead of our pwa. We need to be consisted. 
Question is: you think we need to rename them all to our doc or stay as magento?

File: Model/Resolver/Reorder.php [hunk 3]
```diff
@@ -0,0 +1,102 @@
...
+            $reorder,
+            $orderFactory
+        );
+
+        $this->orderFactory = $orderFactory;
+        $this->reorder = $reorder;
+    }
+
+    /**
+     * @inheritDoc
```
Comment (aleksandrsm) [inline Model/Resolver/Reorder.php]: could use a comment on the purpose of the rewrite
which was to remove the store id filter from the order load

**Review by aleksandrsm — CHANGES_REQUESTED** [review]
minor code style comments

File: Model/Resolver/Reorder.php (hunk 1 above)
Comment (aleksandrsm) [reply Model/Resolver/Reorder.php:2]: Agreed on consistency.
And I'd say that we need to rename them all.

**Review by aleksandrsm — APPROVED** [review]
